# Generated by Django 4.2.7 on 2023-11-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.items')),
            ],
        ),
    ]
